application: evaporatejs
version: evaporate-214
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /
  static_files: evaporate_example.html
  upload: evaporate_example.html

- url: /lambda
  static_fil